

run_trivial:
	nvcc -o trivial_reduce trivial_reduce.cu && ./trivial_reduce 

run_thread:
	nvcc -o thread_reduce thread_reduce.cu && ./thread_reduce 

run_block:
	nvcc -o block_reduce block_reduce.cu && ./block_reduce 